language: node_js
notifications:
  email:
    on_success: never
    on_failure: never
node_js:
  - '0.12'
script:
  - npm run-script deploy
env:
  global:
    - secure: i7hlxT6ToVuaPOv9Ikq87FbjpOvkRiagXW43fvva1HjEHd++P2v/kkKsvoXk/LNaA0BFR0Ic+MjEw9klXrLg3l6i9VTQv9eORyOiKLwC7pXk/DmSLnOjkvMpEkZKioiWuh8HQn87nS+bRUR8GIsiyl84LrTQ2l04cHoR1ii3mCs=
